Frequency <- c(0.6,0.3,0.4,0.4,0.2,0.6,0.3,0.4,0.9,0.2)
BP <- c(103,87,32,42,59,109,78,205,135,176)
First <- c(1,1,1,1,0,0,0,0,NA,1)
Second <- c(0,0,1,1,0,0,1,1,1,1)
Final <-c(0,1,0,1,0,1,0,1,1,1)
hospital.df <- data.frame(Frequency,BP,First,Second,Final)
hospital.df
mean(Final)
mean(BP)
par(mfrow=c(1,5))   
hist(hospital.df$BP,col= "green",main="Histogram of the BP variable")
hist(hospital.df$Frequency,col="red",main="Histogram of the Frequency variable")
hist(hospital.df$First,col="purple",main="Histogram of the First variable")
hist(hospital.df$Second,col="yellow",main="Histogram of the Second variable")
hist(hospital.df$Final,col="brown",main="Histogram of the Final variable")
par(mfrow=c(1,5))   
boxplot(hospital.df$BP,col= "green",main="boxplot of the BP variable")
boxplot(hospital.df$Frequency,col="red",main="boxplot of the Frequency variable")
boxplot(hospital.df$First,col="purple",main="boxplotof the First variable")
boxplot(hospital.df$Second,col="yellow",main="boxplot of the Second variable")
boxplot(hospital.df$Final,col="brown",main="boxplot of the Final variable")

